import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link"
import './globals.css'
import { getPages } from '@/sanity/sanity-utils'
import Navo from './components/Navo'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Racing car',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-200`}>
        <header className="bg-black text-gray-200">
          <Link href="/">home</Link>
          <Link href="/">about</Link>
          <Link href="/history">history</Link>
          
        </header>
        <div>
        <Navo></Navo>
        </div>
        <main>{children}</main>
      </body>
    </html>
  )
}
